let schoolsList = [
  {
    id: 1,
    name: "Excella School",
    type: "primary",
    location: "Kimironko",
    telephone: "+250-788306085",
    is_allowed_to_reopen: false,
    is_international: false,
  },
  {
    id: 2,
    name: "Belgian School",
    type: "primary",
    location: "Kigali",
    telephone: "+250-252576635",
    is_allowed_to_reopen: false,
    is_international: true,
  },
  {
    id: 3,
    name: "Kigali Parent School",
    type: "primary",
    location: "Nyandungu Rwamagana Road",
    telephone: "+250 (0) 252 584754",
    is_allowed_to_reopen: false,
    is_international: false,
  },
  {
    id: 4,
    name: "Green Hills Academy",
    type: "primary",
    location: "Nyarutarama",
    telephone: "+250 (0) 252 580746",
    is_allowed_to_reopen: false,
    is_international: false,
  },
  {
    id: 5,
    name: "Green Hills Academy",
    type: "primary",
    location: "Nyarutarama",
    telephone: "+250 (0) 252 580746",
    is_allowed_to_reopen: false,
    is_international: false,
  },
  {
    id: 6,
    name: "Kinunga Primary School",
    type: "primary",
    location: " Kinunga",
    telephone: "+250-78522720",
    is_allowed_to_reopen: false,
    is_international: false,
  },
  {
    id: 7,
    name: "Camp Kigali Primary School",
    type: "primary",
    location: " Camp Kigali",
    telephone: "+250-788453170",
    is_allowed_to_reopen: false,
    is_international: false,
  },
  {
    id: 8,
    name: "Fawe Girls School",
    type: "secondary",
    location: " Kigali",
    telephone: "+250 (0) 252 585214",
    is_allowed_to_reopen: false,
    is_international: false,
  },
  {
    id: 9,
    name: "Sunrise High School",
    type: "secondary",
    location: "Musanze, Rwanda",
    telephone: "+250 (0) 252 55108807",
    is_allowed_to_reopen: false,
    is_international: false,
  },
  {
    id: 10,
    name: "Riviera High School",
    type: "secondary",
    location: "Kigali, Rwanda",
    telephone: "+250 772 506438",
    is_allowed_to_reopen: false,
    is_international: false,
  },
  {
    id: 11,
    name: "La Colombiere",
    type: "secondary",
    location: "Kimicanga,Gasabo District",
    telephone: "+250 (0) 252 574485",
    is_allowed_to_reopen: false,
    is_international: false,
  },
  {
    id: 12,
    name: "Kigali Parents School",
    type: "secondary",
    location: "Nyandungu Rwamagana Road",
    telephone: "+250 (0) 252 584754",
    is_allowed_to_reopen: false,
    is_international: false,
  },
  {
    id: 13,
    name: "Kigali international Community School",
    type: "international",
    location: "Caisse Sociale Estates",
    telephone: "+250-783307282",
    is_allowed_to_reopen: false,
    is_international: true,
  },
  {
    id: 14,
    name: "Hagos International Schoo",
    type: "international",
    location: "Green house, Avenue Du Lac Kivu",
    telephone: "+250-784577880",
    is_allowed_to_reopen: false,
    is_international: true,
  },
  {
    id: 15,
    name: "International School of Kigali",
    type: "international",
    location: "Avenue Du Commerce",
    telephone: "+250788302899",
    is_allowed_to_reopen: false,
    is_international: true,
  },
  {
    id: 16,
    name: "Riviera High School",
    type: "international",
    location: "Located at Kabuga",
    telephone: "+250 788 305 655",
    is_allowed_to_reopen: false,
    is_international: true,
  },
  {
    id: 17,
    name: "Hope Kids Academy(Rwandan Turkish International School)",
    type: "international",
    location: "Behind Uganda High Commission, Nyarutama",
    telephone: "+250-280382298",
    is_allowed_to_reopen: false,
    is_international: true,
  },
  {
    id: 18,
    name: "University of Rwanda",
    type: "university",
    location: "provinces",
    telephone: "N/A",
    is_allowed_to_reopen: false,
    is_international: true,
  },
  {
    id: 19,
    name: "Kigali Independent University",
    type: "university",
    location: "provinces",
    telephone: "N/A",
    is_allowed_to_reopen: false,
    is_international: true,
  },
  {
    id: 20,
    name: "The Adventist University",
    type: "university",
    location: "provinces",
    telephone: "N/A",
    is_allowed_to_reopen: false,
    is_international: true,
  },
];
export default schoolsList;
